config/routes.rb
Rails.application.routes.draw do
  resources :authors
  root 'posts#index'
  resources :apidocs, only: [:index]
  resources :posts 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  validates :name, presence: true
  enum gender: [:male, :female, :others]
  include Swagger::Blocks
  swagger_schema :Author do
    key :required, [:id, :name]
    property :name do
      key :type, :string
    end
    property :country do
      key :type, :string
    end
    property :gender do
      key :type, :string
    end
  end

  swagger_schema :AuthorInput do
    allOf do
      schema do
        key :'$ref', :Author
      end
      schema do
        key :required, [:name]
      end
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  include Swagger::Blocks
  swagger_path '/authors/{id}' do
    operation :get do
      key :description, 'Returns a single Post if the user has access'
      key :operationId, 'findPostById'
      parameter do
        key :name, :Authoraization
        key :in, :header
        key :description, 'Authoraization'
        key :required, true
        key :type, :string
      end
      parameter do
        key :name, :id
        key :in, :path
        key :description, 'ID of Post to fetch'
        key :required, true
        key :type, :string
        key :format, :int64
      end
      response 200 do
        key :description, 'Author response'
        schema do
          key :'$ref', :Author
        end
      end
      response :default do
        key :description, 'unexpected error'
        schema do
          key :'$ref', :ErrorModel
        end
      end
    end
    operation :patch do
      parameter do
        key :name, :id
        key :in, :path
        key :description, 'ID of Author to fetch'
        key :required, true
        key :type, :string
        key :format, :int64
      end
      parameter do
        key :name, :post
        key :in, :body
        key :description, 'Author to add to the store'
        key :required, true
        schema do
          key :'$ref', :AuthorInput
        end
      end
    end
    operation :delete do
      parameter do
        key :name, :id
        key :in, :path
        key :description, 'ID of Author to fetch'
        key :required, true
        key :type, :string
        key :format, :int64
      end
    end
  end
  swagger_path '/authors' do
    operation :get do
      key :description, 'Returns all Author from the system that the user has access to'
      key :operationId, 'findAuthors'
      key :produces, [
                       'application/json',
                       'text/html',
                   ]
      parameter do
        key :name, :limit
        key :in, :query
        key :description, 'maximum number of results to return'
        key :required, false
        key :type, :integer
        key :format, :int32
      end
      response 200 do
        key :description, 'Author response'
        schema do
          key :type, :array
          items do
            key :'$ref', :Author
          end
        end
      end
      response :default do
        key :description, 'unexpected error'
        schema do
          key :'$ref', :ErrorModel
        end
      end
    end
    operation :post do
      key :description, 'Creates a new author in the store.  Duplicates are allowed'
      key :operationId, 'addAuthor'
      key :produces, [
                       'application/json'
                   ]
      parameter do
        key :name, :post
        key :in, :body
        key :description, 'author to add to the store'
        key :required, true
        schema do
          key :'$ref', :AuthorInput
        end
      end
      response 200 do
        key :description, 'author response'
        schema do
          key :'$ref', :Author
        end
      end
      response :default do
        key :description, 'unexpected error'
        schema do
          key :'$ref', :ErrorModel
        end
      end
    end
  end
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :country, :gender)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for(author) do |f| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.number_field :gender %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.country %></td>
        <td><%= author.gender %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @author.country %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @author.gender %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>